import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "@/styles/globals.css";
import NavWrapper from "@/components/navbar/NavWrapper";
import SmoothScroll from "@/components/ui/SmoothScroll";
import BackToTop from "@/components/ui/BackToTop";
import MouseEffect from "@/components/ui/MouseEffect";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

const SITE_URL = "https://sabbirmusfique.com.bd";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Mohammad Sabbir Musfique | Software Engineer",
    template: "%s | Mohammad Sabbir Musfique",
  },
  description:
    "Software engineer building full-stack web systems, mobile apps, and AI-powered solutions. Specializing in MERN, Flutter, Spring Boot, and Machine Learning.",
  keywords: [
    "Mohammad Sabbir Musfique",
    "Software Engineer",
    "Full Stack Developer",
    "Flutter Developer",
    "AI/ML Engineer",
    "Python",
    "TypeScript",
    "Spring Boot",
    "MERN Stack",
    "Bangladesh",
    "Portfolio",
    "Web Development",
    "Mobile App Development",
    "Machine Learning",
  ],
  authors: [{ name: "Mohammad Sabbir Musfique", url: SITE_URL }],
  creator: "Mohammad Sabbir Musfique",
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Mohammad Sabbir Musfique",
    title: "Mohammad Sabbir Musfique | Software Engineer",
    description:
      "Software engineer building full-stack web systems, mobile apps, and AI-powered solutions.",
    // og:image is generated by app/opengraph-image.tsx (1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: "Mohammad Sabbir Musfique | Software Engineer",
    description:
      "Software engineer building full-stack web systems, mobile apps, and AI-powered solutions.",
    // twitter:image falls back to the generated opengraph-image.
  },
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
  alternates: {
    canonical: SITE_URL,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${inter.variable}`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='light'){document.documentElement.classList.remove('dark')}else{document.documentElement.classList.add('dark')}}catch(e){document.documentElement.classList.add('dark')}})();` }} />
      </head>
      <body className="bg-background text-on-surface selection:bg-primary/30 min-h-screen overflow-x-hidden soft-grid antialiased" suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "Person",
                  "@id": `${SITE_URL}/#person`,
                  name: "Mohammad Sabbir Musfique",
                  url: SITE_URL,
                  image: `${SITE_URL}/sabbir_musfique.png`,
                  jobTitle: "Software Engineer",
                  description:
                    "Software engineer building production systems across full stack, AI/ML, and mobile. Java, Spring Boot, React, Node.js, and Flutter.",
                  address: {
                    "@type": "PostalAddress",
                    addressLocality: "Dhaka",
                    addressCountry: "BD",
                  },
                  worksFor: {
                    "@type": "Organization",
                    name: "Be Data Solutions",
                  },
                  alumniOf: {
                    "@type": "CollegeOrUniversity",
                    name: "MIST (Military Institute of Science and Technology)",
                  },
                  knowsAbout: [
                    "React",
                    "Next.js",
                    "Flutter",
                    "Java",
                    "Spring Boot",
                    "Node.js",
                    "Python",
                    "TensorFlow",
                    "PostgreSQL",
                    "TypeScript",
                  ],
                  sameAs: [
                    "https://github.com/sabbir-063",
                    "https://linkedin.com/in/msmusfique063",
                  ],
                },
                {
                  "@type": "WebSite",
                  "@id": `${SITE_URL}/#website`,
                  url: SITE_URL,
                  name: "Mohammad Sabbir Musfique",
                  description:
                    "Portfolio of Mohammad Sabbir Musfique — software engineer specializing in full stack, AI/ML, and mobile development.",
                  inLanguage: "en",
                  publisher: { "@id": `${SITE_URL}/#person` },
                },
              ],
            }),
          }}
        />
        <SmoothScroll>
          <MouseEffect />
          <NavWrapper />
          {children}
          <BackToTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
