import type { IconBaseProps, IconType } from "react-icons";
import {
  MdArrowBack,
  MdArrowForward,
  MdArrowUpward,
  MdArticle,
  MdAutorenew,
  MdBarChart,
  MdBusiness,
  MdCalendarToday,
  MdCheck,
  MdCheckCircle,
  MdClose,
  MdDarkMode,
  MdDescription,
  MdEditNote,
  MdError,
  MdExpandLess,
  MdExpandMore,
  MdFolderOpen,
  MdForum,
  MdHandshake,
  MdHandyman,
  MdHome,
  MdHub,
  MdKeyboardArrowDown,
  MdLightMode,
  MdLocationOn,
  MdMail,
  MdMenu,
  MdOpenInNew,
  MdPerson,
  MdPhoneIphone,
  MdPsychology,
  MdReply,
  MdRocketLaunch,
  MdSchedule,
  MdSchool,
  MdSearch,
  MdSearchOff,
  MdSend,
  MdTerminal,
  MdWeb,
  MdWork,
} from "react-icons/md";

const icons = {
  arrow_back: MdArrowBack,
  arrow_forward: MdArrowForward,
  arrow_upward: MdArrowUpward,
  article: MdArticle,
  bar_chart: MdBarChart,
  business: MdBusiness,
  calendar_today: MdCalendarToday,
  check: MdCheck,
  check_circle: MdCheckCircle,
  close: MdClose,
  dark_mode: MdDarkMode,
  description: MdDescription,
  edit_note: MdEditNote,
  error: MdError,
  expand_less: MdExpandLess,
  expand_more: MdExpandMore,
  folder_open: MdFolderOpen,
  forum: MdForum,
  handshake: MdHandshake,
  handyman: MdHandyman,
  home: MdHome,
  hub: MdHub,
  keyboard_arrow_down: MdKeyboardArrowDown,
  light_mode: MdLightMode,
  location_on: MdLocationOn,
  mail: MdMail,
  menu: MdMenu,
  open_in_new: MdOpenInNew,
  person: MdPerson,
  phone_iphone: MdPhoneIphone,
  progress_activity: MdAutorenew,
  psychology: MdPsychology,
  reply: MdReply,
  rocket_launch: MdRocketLaunch,
  schedule: MdSchedule,
  school: MdSchool,
  search: MdSearch,
  search_off: MdSearchOff,
  send: MdSend,
  terminal: MdTerminal,
  web: MdWeb,
  work: MdWork,
} satisfies Record<string, IconType>;

export type AppIconName = keyof typeof icons;

interface AppIconProps extends Omit<IconBaseProps, "children"> {
  name: AppIconName;
}

export default function AppIcon({ name, ...props }: AppIconProps) {
  const Icon = icons[name];
  return <Icon aria-hidden="true" focusable="false" {...props} />;
}
